### PR TITLE
feat: done plugin inner & adjust the directory

### PR DESCRIPTION
**Pull request by myNameIsDu**
- [x] done plugin inner & adjust the directory
- [x] done plugin outer
- [x]  done actions
- [x] add feature: summarize the ts statement file
- [x] finishing types
- [x] add test actions

### CODE REVIEW

**Review by bigbigDreamer — COMMENTED** [review]
hi, du, I think we can ignore test files, perhaps we can write a new lint config for test files.

**Comment by bigbigDreamer** [comment]
> hi, du, I think we can ignore test files, perhaps we can write a new lint config for test files.

@myNameIsDu

**Comment by myNameIsDu** [comment]
> hi, du, I think we can ignore test files, perhaps we can write a new lint config for test files.

Why do that

**Comment by bigbigDreamer** [comment]
> > hi, du, I think we can ignore test files, perhaps we can write a new lint config for test files.
> 
> Why do that

test's lint rules do not match normal project file's lint rule

**Comment by myNameIsDu** [comment]
@bigbigDreamer  I haven't felt it yet. Any examples?

**Pull request merged**
